// data.ts

export class MyData {
  static sampleCompanies = [
    {
      DomainName: "example.com",
      CompanyName: "Example Corp",
      CompanyOwner: "John Doe",
      CompanyIndustry: "Healthcare",
      CompanyIndustryType: "Healthcare",
      HeadCount: 500,
      AnnualRevenue: "5M",
      City: "Toronto",
      State: "New York State",
      Country: "Australia",
      PostalCode: "12345",
      TimeZone: "pst",
      Website: "http://www.example.com",
      LinkedinUrl: "http://www.linkedin.com/company/example",
      BusinessEmail: "contact@example.com",
      CompanyAddress1: "123 Example Street",
      CampanyAddress2: "Suite 100",

    },
    {
      DomainName : "aaa.com",
      CompanyName : "aaa Corp",
      CompanyOwner : "John Doe",
      CompanyIndustry : "Technology",
      CompanyIndustryType : "Technology",
      HeadCount : 500,
      AnnualRevenue : "5M",
      City : "Vancouver",
      State : "California",
      Country : "Canada",
      PostalCode : "12345",
      TimeZone : "pst",
      Website : "http://www.aaa.com",
      LinkedinUrl : "http://www.linkedin.com/company/aaa",
      BusinessEmail : "contact@aaa.com",
      CompanyAddress1 : "123 aaa Street",
      CampanyAddress2 : "Suite 100",
    },
    // {
    //   "domainName": "example1.com",
    //   "companyName": "Tech Innovations Inc.",
    //   "companyOwner": "John Doe",
    //   "headCount": 120,
    //   "annualRevenue": 2500000,
    //   "postalCode": "90210",
    //   "linkedinUrl": "https://www.linkedin.com/in/johndoe",
    //   "businessEmail": "contact@example1.com",
    //   "website": "https://www.example1.com",
    //   "companyAddress1": "123 Tech Street",
    //   "companyAddress2": "Suite 200",
    //   "companyIndustry": "Healthcare",
    //   "companyIndustryType": "Healthcare",
    //   "city": "Toronto",
    //   "state": "New York State",
    //   "country": "Canada",
    //   "timeZone": "pst"
    // },
    // {
    //   "domainName": "example2.net",
    //   "companyName": "Global Solutions LLC",
    //   "companyOwner": "Jane Smith",
    //   "headCount": 85,
    //   "annualRevenue": 1500000,
    //   "postalCode": "30301",
    //   "linkedinUrl": "https://www.linkedin.com/in/janesmith",
    //   "businessEmail": "info@example2.net",
    //   "website": "https://www.example2.net",
    //   "companyAddress1": "456 Global Ave",
    //   "companyAddress2": "Floor 3",
    //   "companyIndustry": "Technology",
    //   "companyIndustryType": "Technology",
    //   "city": "Vancouver",
    //   "state": "California",
    //   "country": "Australia",
    //   "timeZone": "PST"
    // },
    // {
    //   "domainName": "example3.org",
    //   "companyName": "Eco Friendly Co.",
    //   "companyOwner": "Alice Johnson",
    //   "headCount": 60,
    //   "annualRevenue": 900000,
    //   "postalCode": "10001",
    //   "linkedinUrl": "https://www.linkedin.com/in/alicejohnson",
    //   "businessEmail": "contact@example3.org",
    //   "website": "https://www.example3.org",
    //   "companyAddress1": "789 Eco Way",
    //   "companyAddress2": "Building A",
    //   "companyIndustry": "Education",
    //   "companyIndustryType": "Education",
    //   "city": "London",
    //   "state": "Ontario",
    //   "country": "Germany",
    //   "timeZone": "pst"
    // }
  ]
    ;
}
